site_name: Camfurbush Docs
theme:
  palette:
    scheme: slate
  name: material
  icon:
      logo: material/bookshelf
repo_url: https://github.com/Camfurbush/camfurbush
repo_name: Camfurbush/camfurbush
